/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misemanasanta01;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author ManuPortatil
 */
public class BandasGUI extends javax.swing.JFrame {

    /**
     * Creates new form Finanzas
     */
    
    //Modelo de la lista de Agrupaciones Musicales
    DefaultListModel modeloAM = new DefaultListModel();
    DefaultListModel modeloCCTT = new DefaultListModel();
    
    public BandasGUI() {
                        
        initComponents();
        //Le ponemos un marco la ventana
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(3, 3, 3, 3, Color.BLUE));
        
        //Grupo de botones de radio
        ButtonGroup grupoTipoBandas = new ButtonGroup();
        grupoTipoBandas.add(jRadioButtonAM);
        grupoTipoBandas.add(jRadioButtonCCTT);
        
        //Cargamos las bandas en el ListBox
        //jListBandasCristo.ad
        //jListBandasCristo.add(VentanaPrincipal.arrayAgrupaciones[0].getNombreAgrupacion());
        for(int x = 0; x < VentanaPrincipal.arrayAgrupaciones.length; x++)  {
            modeloAM.addElement(VentanaPrincipal.arrayAgrupaciones[x].getNombreAgrupacion());
        }
        for(int x = 0; x < VentanaPrincipal.arrayCCTT.length; x++)  {
            modeloCCTT.addElement(VentanaPrincipal.arrayCCTT[x].getNombreAgrupacion());
        }
        //Solo se puede seleccionar un elemento a la vez en la lista
        jListBandasCristo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //Por defecto aparece marcado el primer elemento
        jListBandasCristo.setSelectedIndex(0);
        jLabelCiudadBanda.setText(VentanaPrincipal.arrayAgrupaciones[0].getCiudad());
        jLabelComponenteBanda.setText("" + VentanaPrincipal.arrayAgrupaciones[0].getComponentes());
        jLabelPrecioBanda.setText("" + VentanaPrincipal.arrayAgrupaciones[0].getPrecio());
        jLabelTipoBanda.setText("Agrupación Musical");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelBandaMisterio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelComponenteBanda = new javax.swing.JLabel();
        jLabelCiudadBanda = new javax.swing.JLabel();
        jLabelTipoBanda = new javax.swing.JLabel();
        jLabelPrecioBanda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListBandasCristo = new javax.swing.JList<>();
        jRadioButtonCCTT = new javax.swing.JRadioButton();
        jRadioButtonAM = new javax.swing.JRadioButton();
        jPanelBandaPalio = new javax.swing.JPanel();

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Escoge Banda:");

        jButton2.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Contratar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Componentes:");

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Ciudad:");

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Tipo:");

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("PRECIO:");

        jLabelComponenteBanda.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabelComponenteBanda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComponenteBanda.setText("jLabel7");

        jLabelCiudadBanda.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabelCiudadBanda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCiudadBanda.setText("jLabel7");

        jLabelTipoBanda.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabelTipoBanda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoBanda.setText("jLabel7");

        jLabelPrecioBanda.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        jLabelPrecioBanda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecioBanda.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelComponenteBanda, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCiudadBanda, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTipoBanda, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPrecioBanda, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelComponenteBanda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelCiudadBanda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelTipoBanda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelPrecioBanda))
                .addGap(38, 38, 38))
        );

        jListBandasCristo.setModel(modeloAM);
        jListBandasCristo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListBandasCristoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListBandasCristo);

        jRadioButtonCCTT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonCCTT.setForeground(new java.awt.Color(51, 0, 255));
        jRadioButtonCCTT.setText("Cornetas y Tambores");
        jRadioButtonCCTT.setFocusable(false);
        jRadioButtonCCTT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButtonCCTT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jRadioButtonCCTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCCTTActionPerformed(evt);
            }
        });

        jRadioButtonAM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonAM.setForeground(new java.awt.Color(153, 51, 0));
        jRadioButtonAM.setSelected(true);
        jRadioButtonAM.setText("Agrupación Musical");
        jRadioButtonAM.setFocusable(false);
        jRadioButtonAM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jRadioButtonAM.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jRadioButtonAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBandaMisterioLayout = new javax.swing.GroupLayout(jPanelBandaMisterio);
        jPanelBandaMisterio.setLayout(jPanelBandaMisterioLayout);
        jPanelBandaMisterioLayout.setHorizontalGroup(
            jPanelBandaMisterioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBandaMisterioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBandaMisterioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBandaMisterioLayout.createSequentialGroup()
                        .addComponent(jRadioButtonCCTT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jRadioButtonAM)
                        .addGap(553, 553, 553))
                    .addGroup(jPanelBandaMisterioLayout.createSequentialGroup()
                        .addGroup(jPanelBandaMisterioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelBandaMisterioLayout.setVerticalGroup(
            jPanelBandaMisterioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBandaMisterioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanelBandaMisterioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCCTT)
                    .addComponent(jRadioButtonAM))
                .addGap(18, 18, 18)
                .addGroup(jPanelBandaMisterioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Banda Paso de Misterio", jPanelBandaMisterio);

        javax.swing.GroupLayout jPanelBandaPalioLayout = new javax.swing.GroupLayout(jPanelBandaPalio);
        jPanelBandaPalio.setLayout(jPanelBandaPalioLayout);
        jPanelBandaPalioLayout.setHorizontalGroup(
            jPanelBandaPalioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 904, Short.MAX_VALUE)
        );
        jPanelBandaPalioLayout.setVerticalGroup(
            jPanelBandaPalioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Banda Paso Palio", jPanelBandaPalio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose(); //Destruimos la instancia de esta ventana
        MiSemanaSanta01.ventanaPrincipal.setEnabled(true); //Activamos la ventana principal
        MiSemanaSanta01.ventanaPrincipal.setVisible(true); //Hacemos visible la ventana principal
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButtonCCTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCCTTActionPerformed
        jListBandasCristo.setModel(modeloCCTT);
        
    }//GEN-LAST:event_jRadioButtonCCTTActionPerformed

    private void jRadioButtonAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAMActionPerformed
        jListBandasCristo.setModel(modeloAM);
        
    }//GEN-LAST:event_jRadioButtonAMActionPerformed

    private void jListBandasCristoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListBandasCristoValueChanged
        if(evt.getValueIsAdjusting()) { //Solo me interesa cuando la opción está siendo seleccionada, no me interesa cuando la opción se desselecciona
            if(jRadioButtonAM.isSelected()) {
                System.out.println("AM" + jListBandasCristo.getSelectedIndex());
                jLabelCiudadBanda.setText(VentanaPrincipal.arrayAgrupaciones[jListBandasCristo.getSelectedIndex()].getCiudad());
                jLabelComponenteBanda.setText("" + VentanaPrincipal.arrayAgrupaciones[jListBandasCristo.getSelectedIndex()].getComponentes());             
                jLabelPrecioBanda.setText("" + VentanaPrincipal.arrayAgrupaciones[jListBandasCristo.getSelectedIndex()].getPrecio());
                if(VentanaPrincipal.arrayAgrupaciones[jListBandasCristo.getSelectedIndex()].isTipo())
                        jLabelTipoBanda.setText("Banda de CCTT");
                else 
                    jLabelTipoBanda.setText("Agrupación Musical");
            }
            if(jRadioButtonCCTT.isSelected()) {
                System.out.println("CT" + jListBandasCristo.getSelectedIndex());
                jLabelCiudadBanda.setText(VentanaPrincipal.arrayCCTT[jListBandasCristo.getSelectedIndex()].getCiudad());
                jLabelComponenteBanda.setText("" + VentanaPrincipal.arrayCCTT[jListBandasCristo.getSelectedIndex()].getComponentes());                
                jLabelPrecioBanda.setText("" + VentanaPrincipal.arrayCCTT[jListBandasCristo.getSelectedIndex()].getPrecio());
                if(VentanaPrincipal.arrayCCTT[jListBandasCristo.getSelectedIndex()].isTipo())
                        jLabelTipoBanda.setText("Banda de CCTT");
                else 
                    jLabelTipoBanda.setText("Agrupación Musical");
            }
        }
    }//GEN-LAST:event_jListBandasCristoValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCiudadBanda;
    private javax.swing.JLabel jLabelComponenteBanda;
    private javax.swing.JLabel jLabelPrecioBanda;
    private javax.swing.JLabel jLabelTipoBanda;
    private javax.swing.JList<String> jListBandasCristo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBandaMisterio;
    private javax.swing.JPanel jPanelBandaPalio;
    private javax.swing.JRadioButton jRadioButtonAM;
    private javax.swing.JRadioButton jRadioButtonCCTT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
