/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misemanasanta01;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

/**
 *
 * @author ManuPortatil
 */
public class EnseresGUI extends javax.swing.JFrame {

    /**
     * Creates new form Enseres
     */
    
    static public ImageIcon imagenesEnser;
    //Strings usados para formar la cadena de la ruta de la imagen del Cristo
    String cadena1, cadena2;
    //Numero del Cristo
    int numeroEnser;
    
    public EnseresGUI() {
        initComponents();
        //Le ponemos un marco la ventana
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(3, 3, 3, 3, Color.BLUE));
        
        //Imagenes de Cristo
        imagenesEnser = new ImageIcon(getClass().getResource("/misemanasanta01/Graficos/Enseres/Enser01_210x276.png"));
        cadena1 = "/misemanasanta01/Graficos/Enseres/Enser";
        cadena2 = "_210x276.png";
        numeroEnser=1;
        
        //Inicializamos las etiquetas correspondientes al Primer Enser
        jLabelEnserPrecio.setText("" + VentanaPrincipal.arrayEnseres[0].getPrecio());        
        jLabelImagenesEnser.setIcon(VentanaPrincipal.arrayEnseres[0].getImagen());
        jLabelEnserMaterial.setText(VentanaPrincipal.arrayEnseres[0].getMaterial());
        jLabelEnserAnio.setText("" + VentanaPrincipal.arrayEnseres[0].getAnio());
        jLabelEnserPeso.setText("" + VentanaPrincipal.arrayEnseres[0].getPeso());
        jLabelEnserTipo.setText(VentanaPrincipal.arrayEnseres[0].getNombreEnser());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCristo = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanelImagenesEnser = new javax.swing.JPanel();
        jLabelImagenesEnser = new javax.swing.JLabel();
        jButtonAnteriorImagen = new javax.swing.JButton();
        jButtonComprarImagen = new javax.swing.JButton();
        jButtonSiguienteImagen = new javax.swing.JButton();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelEnserPrecio = new javax.swing.JLabel();
        jLabelEnserTipo = new javax.swing.JLabel();
        jLabelEnserAnio = new javax.swing.JLabel();
        jLabelAltura = new javax.swing.JLabel();
        jLabelPeso = new javax.swing.JLabel();
        jLabelEnserPeso = new javax.swing.JLabel();
        jLabelPeso1 = new javax.swing.JLabel();
        jLabelEnserMaterial = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButtonAnteriorPaso = new javax.swing.JButton();
        jButtonComprarPaso = new javax.swing.JButton();
        jButtonSiguientePaso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelCristo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setFont(new java.awt.Font("Source Serif Pro", 1, 12)); // NOI18N
        jButton2.setText("Comprar Objeto");

        jButton3.setFont(new java.awt.Font("Source Serif Pro", 1, 12)); // NOI18N
        jButton3.setText("Comprar Paso");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 2));

        jPanelImagenesEnser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelImagenesEnser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/misemanasanta01/Graficos/Enseres/Enser01_210x276.png"))); // NOI18N

        javax.swing.GroupLayout jPanelImagenesEnserLayout = new javax.swing.GroupLayout(jPanelImagenesEnser);
        jPanelImagenesEnser.setLayout(jPanelImagenesEnserLayout);
        jPanelImagenesEnserLayout.setHorizontalGroup(
            jPanelImagenesEnserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagenesEnser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelImagenesEnserLayout.setVerticalGroup(
            jPanelImagenesEnserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagenesEnser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButtonAnteriorImagen.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jButtonAnteriorImagen.setText("<");
        jButtonAnteriorImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorImagenActionPerformed(evt);
            }
        });

        jButtonComprarImagen.setText("Comprar");

        jButtonSiguienteImagen.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jButtonSiguienteImagen.setText(">");
        jButtonSiguienteImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteImagenActionPerformed(evt);
            }
        });

        jLabelPrecio.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 12)); // NOI18N
        jLabelPrecio.setText("Precio:");

        jLabelEnserPrecio.setText("0");

        jLabelEnserTipo.setText("0");
        jLabelEnserTipo.setToolTipText("");

        jLabelEnserAnio.setText("0");

        jLabelAltura.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 12)); // NOI18N
        jLabelAltura.setText("Año");

        jLabelPeso.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 12)); // NOI18N
        jLabelPeso.setText("Peso:");

        jLabelEnserPeso.setText("0");

        jLabelPeso1.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 12)); // NOI18N
        jLabelPeso1.setText("Material:");

        jLabelEnserMaterial.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonAnteriorImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonComprarImagen)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonSiguienteImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelImagenesEnser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEnserPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabelAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEnserAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelEnserPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelEnserTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEnserMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanelImagenesEnser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSiguienteImagen)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonComprarImagen)
                                .addComponent(jButtonAnteriorImagen)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelEnserTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAltura)
                            .addComponent(jLabelEnserAnio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPeso)
                            .addComponent(jLabelEnserPeso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPeso1)
                            .addComponent(jLabelEnserMaterial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrecio)
                            .addComponent(jLabelEnserPrecio))
                        .addGap(85, 85, 85))))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0), 2));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jButtonAnteriorPaso.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jButtonAnteriorPaso.setText("<");

        jButtonComprarPaso.setText("Comprar");

        jButtonSiguientePaso.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jButtonSiguientePaso.setText(">");

        jLabel2.setText("Precio:");

        jLabel3.setText("Costaleros:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonAnteriorPaso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jButtonComprarPaso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSiguientePaso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnteriorPaso)
                    .addComponent(jButtonSiguientePaso)
                    .addComponent(jButtonComprarPaso))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCristoLayout = new javax.swing.GroupLayout(jPanelCristo);
        jPanelCristo.setLayout(jPanelCristoLayout);
        jPanelCristoLayout.setHorizontalGroup(
            jPanelCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCristoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCristoLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelCristoLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(31, 457, Short.MAX_VALUE))))
        );
        jPanelCristoLayout.setVerticalGroup(
            jPanelCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCristoLayout.createSequentialGroup()
                .addGroup(jPanelCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 336, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 92, Short.MAX_VALUE)
                .addGroup(jPanelCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Paso de Misterio", jPanelCristo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose(); //Destruimos la instancia de esta ventana
        MiSemanaSanta01.ventanaPrincipal.setEnabled(true); //Activamos la ventana principal
        MiSemanaSanta01.ventanaPrincipal.setVisible(true); //Hacemos visible la ventana principal
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAnteriorImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorImagenActionPerformed
        if(numeroEnser>1) numeroEnser--; //Hay 4 enseres, solo retrocedemos si es mayor de 1
        seleccionarEnser(numeroEnser);

    }//GEN-LAST:event_jButtonAnteriorImagenActionPerformed

    private void jButtonSiguienteImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteImagenActionPerformed
        if(numeroEnser<4) numeroEnser++; //Hay 4 enseres, solo avanzamos si es menor de 4
        //Mostramos los datos del enser a seleccionar
        seleccionarEnser(numeroEnser);

        //jLabelPrecioCristo.setText("" + VentanaPrincipal.miHermandad.getMiCristo().getPrecio());
    }//GEN-LAST:event_jButtonSiguienteImagenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAnteriorImagen;
    private javax.swing.JButton jButtonAnteriorPaso;
    private javax.swing.JButton jButtonComprarImagen;
    private javax.swing.JButton jButtonComprarPaso;
    private javax.swing.JButton jButtonSiguienteImagen;
    private javax.swing.JButton jButtonSiguientePaso;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAltura;
    private javax.swing.JLabel jLabelEnserAnio;
    private javax.swing.JLabel jLabelEnserMaterial;
    private javax.swing.JLabel jLabelEnserPeso;
    private javax.swing.JLabel jLabelEnserPrecio;
    private javax.swing.JLabel jLabelEnserTipo;
    private javax.swing.JLabel jLabelImagenesEnser;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelPeso1;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelCristo;
    private javax.swing.JPanel jPanelImagenesEnser;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    private void seleccionarEnser(int numeroEnser) {
        imagenesEnser = new ImageIcon(getClass().getResource(cadena1 + "0" + numeroEnser + cadena2));
        jLabelEnserPrecio.setText("" + VentanaPrincipal.arrayEnseres[numeroEnser-1].getPrecio());
        jLabelImagenesEnser.setIcon(VentanaPrincipal.arrayEnseres[numeroEnser-1].getImagen());
        jLabelEnserMaterial.setText(VentanaPrincipal.arrayEnseres[numeroEnser-1].getMaterial());
        jLabelEnserAnio.setText("" + VentanaPrincipal.arrayEnseres[numeroEnser-1].getAnio());
        jLabelEnserPeso.setText("" + VentanaPrincipal.arrayEnseres[numeroEnser-1].getPeso());
        jLabelEnserTipo.setText(VentanaPrincipal.arrayEnseres[numeroEnser-1].getNombreEnser());
    }
}
