/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misemanasanta01;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static misemanasanta01.VentanaPrincipal.icono2Dialogos;

/**
 *
 * @author ManuPortatil
 */
public class FinanzasGUI extends javax.swing.JFrame {

    //Variables temporales que almacenan los valores cuando entramos en esta ventana
    int a;
    int b;
    int c;
    int d;
    int e;
    int f;
    int dineroActual;
    //Imagen de icono para los JOptionPane
    static public ImageIcon iconoDialogos;
    
    /**
     * Creates new form Finanzas
     */
    public FinanzasGUI() {
        initComponents();
        //Le ponemos un marco la ventana
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(3, 3, 3, 3, Color.BLUE));
        
        //Guardamos los valores en el momento de entrar en esta ventana
        a = VentanaPrincipal.miHermandad.getPrecioCuotaHermano();
        b = VentanaPrincipal.miHermandad.getPrecioPenitenteMini();
        c = VentanaPrincipal.miHermandad.getPrecioMedalla();
        d = VentanaPrincipal.miHermandad.getPrecioTunica();
        e = VentanaPrincipal.miHermandad.getPrecioPapeletaSitio();
        f = VentanaPrincipal.miHermandad.getPrecioLoteriaNavidad();
        dineroActual = VentanaPrincipal.miHermandad.getDinero();
        //Inicializamos los iconos
        iconoDialogos = new ImageIcon(getClass().getResource("/misemanasanta01/Graficos/Monedas.png"));
        //Establecemos el nombre de la hermandad en el label
        //jLabelNombreHermandad.setText(MiSemanaSanta01.nombreHermandad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jLabelNombreHermandad = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelIngresosVariables = new javax.swing.JPanel();
        jPanelIngresosMensuales = new javax.swing.JPanel();
        jLabelCuotaHermano = new javax.swing.JLabel();
        jSliderCuotaHermano = new javax.swing.JSlider();
        jTextFieldCuotaMensual = new javax.swing.JTextField();
        jPanelIngresosAnuales = new javax.swing.JPanel();
        jLabelPapeletaSitio = new javax.swing.JLabel();
        jSliderPapeletaSitio = new javax.swing.JSlider();
        jTextFieldPapeletaSitio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSliderLoteriaNavidad = new javax.swing.JSlider();
        jTextFieldLoteriaNavidad = new javax.swing.JTextField();
        jButtonEstablecer = new javax.swing.JButton();
        jPanelVentas = new javax.swing.JPanel();
        jPanelIngresosVentas = new javax.swing.JPanel();
        jSliderPrecioPenitente = new javax.swing.JSlider();
        jTextFieldPrecioPenitente = new javax.swing.JTextField();
        jLabelPrecioPenitente = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSliderPrecioMedalla = new javax.swing.JSlider();
        jSliderPrecioTunica = new javax.swing.JSlider();
        jTextFieldPrecioMedalla = new javax.swing.JTextField();
        jTextFieldPrecioTunica = new javax.swing.JTextField();
        jButtonEstablecer1 = new javax.swing.JButton();
        jPanelGastos = new javax.swing.JPanel();
        jLabelDonacionONG = new javax.swing.JLabel();
        jLabelDonacionCaritas = new javax.swing.JLabel();
        jSpinnerDonacionONG = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jSpinnerDonacionCaritas = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabelNombreHermandad.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabelNombreHermandad.setForeground(new java.awt.Color(51, 0, 204));
        jLabelNombreHermandad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreHermandad.setText("jLabel1");
        jLabelNombreHermandad.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelNombreHermandad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jTabbedPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 51), 3, true));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jPanelIngresosMensuales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresos Mensuales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanelIngresosMensuales.setForeground(new java.awt.Color(0, 0, 204));
        jPanelIngresosMensuales.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabelCuotaHermano.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCuotaHermano.setText("Cuota mensual hermano: ");

        jSliderCuotaHermano.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSliderCuotaHermano.setMinorTickSpacing(100);
        jSliderCuotaHermano.setValue(0);
        jSliderCuotaHermano.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderCuotaHermanoStateChanged(evt);
            }
        });

        jTextFieldCuotaMensual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldCuotaMensual.setForeground(new java.awt.Color(51, 0, 204));
        jTextFieldCuotaMensual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCuotaMensual.setText("0 €");

        javax.swing.GroupLayout jPanelIngresosMensualesLayout = new javax.swing.GroupLayout(jPanelIngresosMensuales);
        jPanelIngresosMensuales.setLayout(jPanelIngresosMensualesLayout);
        jPanelIngresosMensualesLayout.setHorizontalGroup(
            jPanelIngresosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngresosMensualesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCuotaHermano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSliderCuotaHermano, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldCuotaMensual, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelIngresosMensualesLayout.setVerticalGroup(
            jPanelIngresosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngresosMensualesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIngresosMensualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCuotaMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderCuotaHermano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCuotaHermano))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelIngresosAnuales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresos Anuales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18), new java.awt.Color(0, 153, 153))); // NOI18N
        jPanelIngresosAnuales.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabelPapeletaSitio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPapeletaSitio.setText("Papeleta de sitio:");

        jSliderPapeletaSitio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSliderPapeletaSitio.setMaximum(30);
        jSliderPapeletaSitio.setMinorTickSpacing(100);
        jSliderPapeletaSitio.setValue(0);
        jSliderPapeletaSitio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPapeletaSitioStateChanged(evt);
            }
        });

        jTextFieldPapeletaSitio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldPapeletaSitio.setForeground(new java.awt.Color(51, 0, 204));
        jTextFieldPapeletaSitio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPapeletaSitio.setText("0 €");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Precio Papeleta Lotería Navidad: ");

        jSliderLoteriaNavidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSliderLoteriaNavidad.setMaximum(24);
        jSliderLoteriaNavidad.setMinorTickSpacing(100);
        jSliderLoteriaNavidad.setValue(0);
        jSliderLoteriaNavidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderLoteriaNavidadStateChanged(evt);
            }
        });

        jTextFieldLoteriaNavidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldLoteriaNavidad.setForeground(new java.awt.Color(51, 0, 204));
        jTextFieldLoteriaNavidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldLoteriaNavidad.setText("0 €");

        javax.swing.GroupLayout jPanelIngresosAnualesLayout = new javax.swing.GroupLayout(jPanelIngresosAnuales);
        jPanelIngresosAnuales.setLayout(jPanelIngresosAnualesLayout);
        jPanelIngresosAnualesLayout.setHorizontalGroup(
            jPanelIngresosAnualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngresosAnualesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIngresosAnualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabelPapeletaSitio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelIngresosAnualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderPapeletaSitio, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addComponent(jSliderLoteriaNavidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelIngresosAnualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPapeletaSitio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLoteriaNavidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelIngresosAnualesLayout.setVerticalGroup(
            jPanelIngresosAnualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngresosAnualesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIngresosAnualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldPapeletaSitio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderPapeletaSitio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPapeletaSitio))
                .addGap(18, 18, 18)
                .addGroup(jPanelIngresosAnualesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jSliderLoteriaNavidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLoteriaNavidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jButtonEstablecer.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonEstablecer.setText("ESTABLECER");
        jButtonEstablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstablecerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelIngresosVariablesLayout = new javax.swing.GroupLayout(jPanelIngresosVariables);
        jPanelIngresosVariables.setLayout(jPanelIngresosVariablesLayout);
        jPanelIngresosVariablesLayout.setHorizontalGroup(
            jPanelIngresosVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngresosVariablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIngresosVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIngresosVariablesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonEstablecer))
                    .addGroup(jPanelIngresosVariablesLayout.createSequentialGroup()
                        .addGroup(jPanelIngresosVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelIngresosMensuales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelIngresosAnuales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 191, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelIngresosVariablesLayout.setVerticalGroup(
            jPanelIngresosVariablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngresosVariablesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelIngresosMensuales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelIngresosAnuales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jButtonEstablecer)
                .addContainerGap())
        );

        jPanelIngresosAnuales.getAccessibleContext().setAccessibleName("Ingresos");

        jTabbedPane1.addTab("INGRESOS", new javax.swing.ImageIcon(getClass().getResource("/misemanasanta01/Graficos/Monedas.png")), jPanelIngresosVariables); // NOI18N

        jPanelIngresosVentas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ventas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18), new java.awt.Color(153, 102, 0))); // NOI18N
        jPanelIngresosVentas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jSliderPrecioPenitente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSliderPrecioPenitente.setMaximum(10);
        jSliderPrecioPenitente.setMinorTickSpacing(100);
        jSliderPrecioPenitente.setValue(0);
        jSliderPrecioPenitente.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPrecioPenitenteStateChanged(evt);
            }
        });

        jTextFieldPrecioPenitente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldPrecioPenitente.setForeground(new java.awt.Color(51, 0, 204));
        jTextFieldPrecioPenitente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecioPenitente.setText("0 €");

        jLabelPrecioPenitente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPrecioPenitente.setText("Precio Penitente Miniatura:  ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Precio Medalla:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Precio Túnica:");

        jSliderPrecioMedalla.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSliderPrecioMedalla.setMaximum(30);
        jSliderPrecioMedalla.setMinorTickSpacing(100);
        jSliderPrecioMedalla.setValue(0);
        jSliderPrecioMedalla.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPrecioMedallaStateChanged(evt);
            }
        });

        jSliderPrecioTunica.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSliderPrecioTunica.setMaximum(200);
        jSliderPrecioTunica.setMinorTickSpacing(100);
        jSliderPrecioTunica.setValue(0);
        jSliderPrecioTunica.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPrecioTunicaStateChanged(evt);
            }
        });

        jTextFieldPrecioMedalla.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldPrecioMedalla.setForeground(new java.awt.Color(51, 0, 204));
        jTextFieldPrecioMedalla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecioMedalla.setText("0 €");

        jTextFieldPrecioTunica.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldPrecioTunica.setForeground(new java.awt.Color(51, 0, 204));
        jTextFieldPrecioTunica.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecioTunica.setText("0 €");

        javax.swing.GroupLayout jPanelIngresosVentasLayout = new javax.swing.GroupLayout(jPanelIngresosVentas);
        jPanelIngresosVentas.setLayout(jPanelIngresosVentasLayout);
        jPanelIngresosVentasLayout.setHorizontalGroup(
            jPanelIngresosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngresosVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIngresosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIngresosVentasLayout.createSequentialGroup()
                        .addGroup(jPanelIngresosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(105, 105, 105)
                        .addComponent(jSliderPrecioTunica, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelIngresosVentasLayout.createSequentialGroup()
                        .addComponent(jLabelPrecioPenitente)
                        .addGap(30, 30, 30)
                        .addGroup(jPanelIngresosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderPrecioMedalla, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSliderPrecioPenitente, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47)
                .addGroup(jPanelIngresosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPrecioPenitente, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelIngresosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldPrecioTunica, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addComponent(jTextFieldPrecioMedalla)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanelIngresosVentasLayout.setVerticalGroup(
            jPanelIngresosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIngresosVentasLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelIngresosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderPrecioPenitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelIngresosVentasLayout.createSequentialGroup()
                        .addGroup(jPanelIngresosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelIngresosVentasLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelPrecioPenitente)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIngresosVentasLayout.createSequentialGroup()
                                .addComponent(jTextFieldPrecioPenitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))
                        .addGroup(jPanelIngresosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelIngresosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jTextFieldPrecioMedalla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSliderPrecioMedalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanelIngresosVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelIngresosVentasLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel10))
                            .addComponent(jTextFieldPrecioTunica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSliderPrecioTunica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonEstablecer1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonEstablecer1.setText("ESTABLECER");
        jButtonEstablecer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstablecer1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVentasLayout = new javax.swing.GroupLayout(jPanelVentas);
        jPanelVentas.setLayout(jPanelVentasLayout);
        jPanelVentasLayout.setHorizontalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVentasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEstablecer1)
                .addContainerGap())
            .addGroup(jPanelVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelIngresosVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanelVentasLayout.setVerticalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelIngresosVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(jButtonEstablecer1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("VENTAS", new javax.swing.ImageIcon(getClass().getResource("/misemanasanta01/Graficos/Billete.png")), jPanelVentas); // NOI18N

        jPanelGastos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanelGastosFocusGained(evt);
            }
        });
        jPanelGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelGastosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelGastosMousePressed(evt);
            }
        });

        jLabelDonacionONG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDonacionONG.setForeground(new java.awt.Color(0, 0, 153));
        jLabelDonacionONG.setText("Realizar Donación a ONG:");

        jLabelDonacionCaritas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDonacionCaritas.setForeground(new java.awt.Color(0, 0, 153));
        jLabelDonacionCaritas.setText("Realizar Donación a Cáritas:");

        jSpinnerDonacionONG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSpinnerDonacionONG.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 51, 0));
        jButton1.setText("DONAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSpinnerDonacionCaritas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSpinnerDonacionCaritas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 51, 0));
        jButton2.setText("DONAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(204, 204, 0));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Donar menos de 100 euros no implicará mejora alguna para la Hermandad.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Si donamos más de 100 euros, podremos mejorar tanto la popularidad como el fervor de la Hermandad.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Cuanto más dones, más subirá, aunque también hay un factor suerte que influye. ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelGastosLayout = new javax.swing.GroupLayout(jPanelGastos);
        jPanelGastos.setLayout(jPanelGastosLayout);
        jPanelGastosLayout.setHorizontalGroup(
            jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGastosLayout.createSequentialGroup()
                .addGroup(jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGastosLayout.createSequentialGroup()
                        .addGroup(jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelGastosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelGastosLayout.createSequentialGroup()
                                        .addComponent(jLabelDonacionCaritas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSpinnerDonacionCaritas, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jButton2))
                                    .addGroup(jPanelGastosLayout.createSequentialGroup()
                                        .addComponent(jLabelDonacionONG, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSpinnerDonacionONG, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jButton1))))
                            .addGroup(jPanelGastosLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 69, Short.MAX_VALUE))
                    .addGroup(jPanelGastosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelGastosLayout.setVerticalGroup(
            jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGastosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDonacionONG, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerDonacionONG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerDonacionCaritas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))
                    .addComponent(jLabelDonacionCaritas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("GASTOS", new javax.swing.ImageIcon(getClass().getResource("/misemanasanta01/Graficos/monedas2.png")), jPanelGastos); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreHermandad, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNombreHermandad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        //Si salimos sin Establecer los valores, volvemos a los valores antiguos
        jSliderCuotaHermano.setValue(VentanaPrincipal.miHermandad.getPrecioCuotaHermano());
        jSliderPrecioPenitente.setValue(VentanaPrincipal.miHermandad.getPrecioPenitenteMini());
        jSliderPrecioMedalla.setValue(VentanaPrincipal.miHermandad.getPrecioMedalla());
        jSliderPrecioTunica.setValue(VentanaPrincipal.miHermandad.getPrecioTunica());
        jSliderPapeletaSitio.setValue(VentanaPrincipal.miHermandad.getPrecioPapeletaSitio());
        jSliderLoteriaNavidad.setValue(VentanaPrincipal.miHermandad.getPrecioLoteriaNavidad());
        this.dispose(); //Destruimos la instancia de esta ventana
        MiSemanaSanta01.ventanaPrincipal.setEnabled(true); //Activamos la ventana principal
        MiSemanaSanta01.ventanaPrincipal.setVisible(true); //Hacemos visible la ventana principal
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jSliderPapeletaSitioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPapeletaSitioStateChanged
        jTextFieldPapeletaSitio.setText("" + jSliderPapeletaSitio.getValue() + " €");
    }//GEN-LAST:event_jSliderPapeletaSitioStateChanged

    private void jSliderCuotaHermanoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderCuotaHermanoStateChanged
        jTextFieldCuotaMensual.setText("" + jSliderCuotaHermano.getValue() + " €");
    }//GEN-LAST:event_jSliderCuotaHermanoStateChanged

    private void jButtonEstablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstablecerActionPerformed
        this.setAlwaysOnTop(false);
        VentanaPrincipal.miHermandad.setPrecioCuotaHermano(jSliderCuotaHermano.getValue());
        VentanaPrincipal.miHermandad.setPrecioPapeletaSitio(jSliderPapeletaSitio.getValue());
        VentanaPrincipal.miHermandad.setPrecioLoteriaNavidad(jSliderLoteriaNavidad.getValue());
        JOptionPane.showMessageDialog(null, "Se ha establecido el precio en los diferentes apartados.", "PRECIO ESTABLECIDO", JOptionPane.OK_OPTION, icono2Dialogos);
        //this.dispose(); //Destruimos la instancia de esta ventana
        //MiSemanaSanta01.ventanaPrincipal.setEnabled(true); //Activamos la ventana principal
        //MiSemanaSanta01.ventanaPrincipal.setVisible(true); //Hacemos visible la ventana principal
        //Mensaje para el Histórico
        MiSemanaSanta01.ventanaPrincipal.escribirHistorico("Se ha establecido el precio en los diferentes apartados.\n\n");
    }//GEN-LAST:event_jButtonEstablecerActionPerformed

    private void jSliderPrecioPenitenteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPrecioPenitenteStateChanged
        jTextFieldPrecioPenitente.setText("" + jSliderPrecioPenitente.getValue() + " €");
    }//GEN-LAST:event_jSliderPrecioPenitenteStateChanged

    private void jSliderPrecioMedallaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPrecioMedallaStateChanged
        jTextFieldPrecioMedalla.setText("" + jSliderPrecioMedalla.getValue() + " €");
    }//GEN-LAST:event_jSliderPrecioMedallaStateChanged

    private void jSliderPrecioTunicaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPrecioTunicaStateChanged
        jTextFieldPrecioTunica.setText("" + jSliderPrecioTunica.getValue() + " €");
    }//GEN-LAST:event_jSliderPrecioTunicaStateChanged

    private void jSliderLoteriaNavidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderLoteriaNavidadStateChanged
        jTextFieldLoteriaNavidad.setText("" + jSliderLoteriaNavidad.getValue() + " €");
    }//GEN-LAST:event_jSliderLoteriaNavidadStateChanged

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if(jTabbedPane1.getSelectedIndex()==0) { 
            this.jButtonEstablecer.setEnabled(true);
        }
        if(jTabbedPane1.getSelectedIndex()==1) { 
            this.jButtonEstablecer.setEnabled(false);
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jPanelGastosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGastosMousePressed
        
    }//GEN-LAST:event_jPanelGastosMousePressed

    private void jPanelGastosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGastosMouseClicked
        
    }//GEN-LAST:event_jPanelGastosMouseClicked

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void jPanelGastosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanelGastosFocusGained
                // TODO add your handling code here:
    }//GEN-LAST:event_jPanelGastosFocusGained

    private void jButtonEstablecer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstablecer1ActionPerformed
        this.setAlwaysOnTop(false);
        //VentanaPrincipal.miHermandad.setPrecioCuotaHermano(jSliderCuotaHermano.getValue());
        VentanaPrincipal.miHermandad.setPrecioPenitenteMini(jSliderPrecioPenitente.getValue());
        VentanaPrincipal.miHermandad.setPrecioMedalla(jSliderPrecioMedalla.getValue());
        VentanaPrincipal.miHermandad.setPrecioTunica(jSliderPrecioTunica.getValue());
        //VentanaPrincipal.miHermandad.setPrecioPapeletaSitio(jSliderPapeletaSitio.getValue());
        //VentanaPrincipal.miHermandad.setPrecioLoteriaNavidad(jSliderLoteriaNavidad.getValue());
        JOptionPane.showMessageDialog(null, "Se ha establecido el precio en los diferentes apartados.", "PRECIO ESTABLECIDO", JOptionPane.OK_OPTION, icono2Dialogos);
        MiSemanaSanta01.ventanaPrincipal.escribirHistorico("Se ha establecido el precio de las ventas en los diferentes apartados.\n\n");
    }//GEN-LAST:event_jButtonEstablecer1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Primero vemos cuánto dinero tenemos
        dineroActual = VentanaPrincipal.miHermandad.getDinero();
        //Después preguntamos si estamos seguros de la donación
        this.setAlwaysOnTop(false);
        int opcion = JOptionPane.showConfirmDialog(null, "Vas a realizar una donación. Confirma la operación", "DONACIÓN", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, icono2Dialogos);
        //Después restamos el dinero y aumentamos la popularidad, siempre que aceptemos
        if(opcion == 0) { //Esto es que ha pulsado SÍ
            VentanaPrincipal.miHermandad.setDinero(dineroActual - (Integer) jSpinnerDonacionONG.getValue()); //Actualizamos el dinero
            MiSemanaSanta01.ventanaPrincipal.jTextFieldDinero.setText("" + VentanaPrincipal.miHermandad.getDinero()); //Actualizamos el jlabel
            int subidaPopularidad = VentanaPrincipal.miHermandad.calcularPopularidad((Integer) jSpinnerDonacionONG.getValue()); //Calculamos cuánto sube la popularidad
            //Mostramos la información en otro panel
            JOptionPane.showMessageDialog(null, "Has donado " + jSpinnerDonacionONG.getValue() + " € a una ONG.\n" +
                    "La popularidad de tu Hermandad ha subido en " + subidaPopularidad + " puntos\n" +
                    "GRACIAS POR TU DONACIÓN", "DONACIÓN", JOptionPane.INFORMATION_MESSAGE);
            MiSemanaSanta01.ventanaPrincipal.escribirHistorico("Has realizado una donación a una ONG.\n\n");
        }
        jSpinnerDonacionONG.setValue(0); //Ponemos el jSpinner a 0
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Primero vemos cuánto dinero tenemos
        dineroActual = VentanaPrincipal.miHermandad.getDinero();
        //Después preguntamos si estamos seguros de la donación
        this.setAlwaysOnTop(false);
        int opcion = JOptionPane.showConfirmDialog(null, "Vas a realizar una donación a Cáritas. Confirma la operación", "DONACIÓN", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, icono2Dialogos);
        //Después restamos el dinero y aumentamos la popularidad, siempre que aceptemos
        if(opcion == 0) { //Esto es que ha pulsado SÍ
            VentanaPrincipal.miHermandad.setDinero(dineroActual - (Integer) jSpinnerDonacionCaritas.getValue()); //Actualizamos el dinero
            MiSemanaSanta01.ventanaPrincipal.jTextFieldDinero.setText("" + VentanaPrincipal.miHermandad.getDinero()); //Actualizamos el jlabel
            int subidaPopularidad = VentanaPrincipal.miHermandad.calcularPopularidad((Integer) jSpinnerDonacionCaritas.getValue()); //Calculamos cuánto sube la popularidad
            //Mostramos la información en otro panel
            JOptionPane.showMessageDialog(null, "Has donado " + jSpinnerDonacionCaritas.getValue() + " € a Cáritas.\n" +
                    "La popularidad de tu Hermandad ha subido en " + subidaPopularidad + " puntos\n" +
                    "GRACIAS POR TU DONACIÓN", "DONACIÓN", JOptionPane.INFORMATION_MESSAGE);
            MiSemanaSanta01.ventanaPrincipal.escribirHistorico("Has realizado una donación a Cáritas.\n\n");
        }
        jSpinnerDonacionCaritas.setValue(0); //Ponemos el jSpinner a 0
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonEstablecer;
    private javax.swing.JButton jButtonEstablecer1;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCuotaHermano;
    private javax.swing.JLabel jLabelDonacionCaritas;
    private javax.swing.JLabel jLabelDonacionONG;
    public javax.swing.JLabel jLabelNombreHermandad;
    private javax.swing.JLabel jLabelPapeletaSitio;
    private javax.swing.JLabel jLabelPrecioPenitente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelGastos;
    private javax.swing.JPanel jPanelIngresosAnuales;
    private javax.swing.JPanel jPanelIngresosMensuales;
    private javax.swing.JPanel jPanelIngresosVariables;
    private javax.swing.JPanel jPanelIngresosVentas;
    private javax.swing.JPanel jPanelVentas;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JSlider jSliderCuotaHermano;
    public javax.swing.JSlider jSliderLoteriaNavidad;
    public javax.swing.JSlider jSliderPapeletaSitio;
    private javax.swing.JSlider jSliderPrecioMedalla;
    private javax.swing.JSlider jSliderPrecioPenitente;
    private javax.swing.JSlider jSliderPrecioTunica;
    private javax.swing.JSpinner jSpinnerDonacionCaritas;
    private javax.swing.JSpinner jSpinnerDonacionONG;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldCuotaMensual;
    private javax.swing.JTextField jTextFieldLoteriaNavidad;
    private javax.swing.JTextField jTextFieldPapeletaSitio;
    private javax.swing.JTextField jTextFieldPrecioMedalla;
    private javax.swing.JTextField jTextFieldPrecioPenitente;
    private javax.swing.JTextField jTextFieldPrecioTunica;
    // End of variables declaration//GEN-END:variables
}
