/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misemanasanta01;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ManuPortatil
 */
public class PasosGUI extends javax.swing.JFrame {

    /**
     * Creates new form Finanzas
     */
    
    //Gráficos de los pasos y las imágenes
    static public ImageIcon imagenesCristo, imagenesPasosCristo;
    //Strings usados para formar la cadena de la ruta de la imagen del Cristo
    String cadena1, cadena2, cadena3, cadena4;
    //Numero del Cristo
    int numeroCristo;
    //Número del Paso
    int numeroPaso;
    
    public PasosGUI() {
        initComponents();
        //Le ponemos un marco la ventana
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(3, 3, 3, 3, Color.BLUE));
        
        //Imagenes de Cristo
        imagenesCristo = new ImageIcon(getClass().getResource("/misemanasanta01/Graficos/Cristos/Cristo00_210x276.png"));
        cadena1 = "/misemanasanta01/Graficos/Cristos/Cristo";
        cadena2 = "_210x276.png";
        numeroCristo = 1;
        
        //Inicializamos las etiquetas correspondientes al Primer Cristo
        jLabelPrecioCristo.setText("" + VentanaPrincipal.arrayCristos[0].getPrecio());
        jLabelImagenesCristo.setIcon(VentanaPrincipal.arrayCristos[0].getImagen());
        jLabelMaterialCristo.setText("" + VentanaPrincipal.arrayCristos[0].getMaterial());
        jLabelAlturaCristo.setText("" + VentanaPrincipal.arrayCristos[0].getAltura());
        jLabelPesoCristo.setText("" + VentanaPrincipal.arrayCristos[0].getPeso());
        
        //Imagenes de Cristo
        imagenesPasosCristo = new ImageIcon(getClass().getResource("/misemanasanta01/Graficos/PasosCristo/Paso00_257x139.png"));
        cadena3 = "/misemanasanta01/Graficos/PasosCristo/Paso";
        cadena4 = "_257x139.png";
        numeroPaso = 1;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCristo = new javax.swing.JPanel();
        jButtonComprarImagenP = new javax.swing.JButton();
        jButtonComprarPasoP = new javax.swing.JButton();
        jPanelComprarCristo = new javax.swing.JPanel();
        jPanelImagenesCristo = new javax.swing.JPanel();
        jLabelImagenesCristo = new javax.swing.JLabel();
        jButtonAnteriorImagen = new javax.swing.JButton();
        jButtonComprarImagen = new javax.swing.JButton();
        jButtonSiguienteImagen = new javax.swing.JButton();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelPrecioCristo = new javax.swing.JLabel();
        jLabelMaterialCristo = new javax.swing.JLabel();
        jLabelAlturaCristo = new javax.swing.JLabel();
        jLabelAltura = new javax.swing.JLabel();
        jLabelPeso = new javax.swing.JLabel();
        jLabelPesoCristo = new javax.swing.JLabel();
        jCheckBoxCristoSeleccionado = new javax.swing.JCheckBox();
        jLabelNCristo = new javax.swing.JLabel();
        jPanelComprarPaso = new javax.swing.JPanel();
        jPanelPaso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAnteriorPaso = new javax.swing.JButton();
        jButtonComprarPaso = new javax.swing.JButton();
        jButtonSiguientePaso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelPalio = new javax.swing.JPanel();

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelCristo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonComprarImagenP.setFont(new java.awt.Font("Source Serif Pro", 1, 12)); // NOI18N
        jButtonComprarImagenP.setText("Comprar Imagen");
        jButtonComprarImagenP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarImagenPActionPerformed(evt);
            }
        });

        jButtonComprarPasoP.setFont(new java.awt.Font("Source Serif Pro", 1, 12)); // NOI18N
        jButtonComprarPasoP.setText("Comprar Paso");

        jPanelComprarCristo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 2));

        jPanelImagenesCristo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelImagenesCristo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/misemanasanta01/Graficos/Cristos/Cristo00_210x276.png"))); // NOI18N

        javax.swing.GroupLayout jPanelImagenesCristoLayout = new javax.swing.GroupLayout(jPanelImagenesCristo);
        jPanelImagenesCristo.setLayout(jPanelImagenesCristoLayout);
        jPanelImagenesCristoLayout.setHorizontalGroup(
            jPanelImagenesCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagenesCristo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelImagenesCristoLayout.setVerticalGroup(
            jPanelImagenesCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagenesCristo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButtonAnteriorImagen.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jButtonAnteriorImagen.setText("<");
        jButtonAnteriorImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorImagenActionPerformed(evt);
            }
        });

        jButtonComprarImagen.setText("Comprar");
        jButtonComprarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarImagenActionPerformed(evt);
            }
        });

        jButtonSiguienteImagen.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jButtonSiguienteImagen.setText(">");
        jButtonSiguienteImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteImagenActionPerformed(evt);
            }
        });

        jLabelPrecio.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 12)); // NOI18N
        jLabelPrecio.setText("Precio:");

        jLabelPrecioCristo.setText("0");

        jLabelMaterialCristo.setText("0");
        jLabelMaterialCristo.setToolTipText("");

        jLabelAlturaCristo.setText("0");

        jLabelAltura.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 12)); // NOI18N
        jLabelAltura.setText("Altura:");

        jLabelPeso.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 12)); // NOI18N
        jLabelPeso.setText("Peso:");

        jLabelPesoCristo.setText("0");

        jCheckBoxCristoSeleccionado.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jCheckBoxCristoSeleccionado.setText("Imagen Actual");
        jCheckBoxCristoSeleccionado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCheckBoxCristoSeleccionado.setBorderPainted(true);
        jCheckBoxCristoSeleccionado.setEnabled(false);

        jLabelNCristo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabelNCristo.setForeground(new java.awt.Color(204, 51, 0));
        jLabelNCristo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNCristo.setText("1 de 10");
        jLabelNCristo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanelComprarCristoLayout = new javax.swing.GroupLayout(jPanelComprarCristo);
        jPanelComprarCristo.setLayout(jPanelComprarCristoLayout);
        jPanelComprarCristoLayout.setHorizontalGroup(
            jPanelComprarCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComprarCristoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComprarCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelComprarCristoLayout.createSequentialGroup()
                        .addComponent(jButtonAnteriorImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonComprarImagen)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonSiguienteImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelImagenesCristo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelComprarCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelComprarCristoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelComprarCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelComprarCristoLayout.createSequentialGroup()
                                .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPrecioCristo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelComprarCristoLayout.createSequentialGroup()
                                .addComponent(jLabelAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAlturaCristo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelComprarCristoLayout.createSequentialGroup()
                                .addComponent(jLabelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPesoCristo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelMaterialCristo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBoxCristoSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelComprarCristoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabelNCristo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelComprarCristoLayout.setVerticalGroup(
            jPanelComprarCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComprarCristoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComprarCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelImagenesCristo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelComprarCristoLayout.createSequentialGroup()
                        .addGroup(jPanelComprarCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrecio)
                            .addComponent(jLabelPrecioCristo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMaterialCristo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelComprarCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAltura)
                            .addComponent(jLabelAlturaCristo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelComprarCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPeso)
                            .addComponent(jLabelPesoCristo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxCristoSeleccionado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelComprarCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelComprarCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSiguienteImagen)
                        .addComponent(jLabelNCristo))
                    .addGroup(jPanelComprarCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonComprarImagen)
                        .addComponent(jButtonAnteriorImagen)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelComprarPaso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0), 2));

        jPanelPaso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/misemanasanta01/Graficos/PasosCristo/Paso00_257x139.png"))); // NOI18N

        javax.swing.GroupLayout jPanelPasoLayout = new javax.swing.GroupLayout(jPanelPaso);
        jPanelPaso.setLayout(jPanelPasoLayout);
        jPanelPasoLayout.setHorizontalGroup(
            jPanelPasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelPasoLayout.setVerticalGroup(
            jPanelPasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButtonAnteriorPaso.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jButtonAnteriorPaso.setText("<");

        jButtonComprarPaso.setText("Comprar");

        jButtonSiguientePaso.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jButtonSiguientePaso.setText(">");

        jLabel2.setText("Precio:");

        jLabel3.setText("Costaleros:");

        javax.swing.GroupLayout jPanelComprarPasoLayout = new javax.swing.GroupLayout(jPanelComprarPaso);
        jPanelComprarPaso.setLayout(jPanelComprarPasoLayout);
        jPanelComprarPasoLayout.setHorizontalGroup(
            jPanelComprarPasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComprarPasoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComprarPasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPaso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelComprarPasoLayout.createSequentialGroup()
                        .addComponent(jButtonAnteriorPaso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jButtonComprarPaso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSiguientePaso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelComprarPasoLayout.createSequentialGroup()
                        .addGroup(jPanelComprarPasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelComprarPasoLayout.setVerticalGroup(
            jPanelComprarPasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComprarPasoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelComprarPasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnteriorPaso)
                    .addComponent(jButtonSiguientePaso)
                    .addComponent(jButtonComprarPaso))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCristoLayout = new javax.swing.GroupLayout(jPanelCristo);
        jPanelCristo.setLayout(jPanelCristoLayout);
        jPanelCristoLayout.setHorizontalGroup(
            jPanelCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCristoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCristoLayout.createSequentialGroup()
                        .addComponent(jPanelComprarCristo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanelComprarPaso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(122, 122, 122))
                    .addGroup(jPanelCristoLayout.createSequentialGroup()
                        .addComponent(jButtonComprarImagenP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonComprarPasoP)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelCristoLayout.setVerticalGroup(
            jPanelCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCristoLayout.createSequentialGroup()
                .addGroup(jPanelCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelComprarCristo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelComprarPaso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 140, Short.MAX_VALUE)
                .addGroup(jPanelCristoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonComprarImagenP)
                    .addComponent(jButtonComprarPasoP))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Paso de Misterio", jPanelCristo);

        jPanelPalio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelPalioLayout = new javax.swing.GroupLayout(jPanelPalio);
        jPanelPalio.setLayout(jPanelPalioLayout);
        jPanelPalioLayout.setHorizontalGroup(
            jPanelPalioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
        );
        jPanelPalioLayout.setVerticalGroup(
            jPanelPalioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Paso de Palio", jPanelPalio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButtonComprarImagenP.setEnabled(true);
        jButtonComprarPasoP.setEnabled(true);
        this.dispose(); //Destruimos la instancia de esta ventana
        MiSemanaSanta01.ventanaPrincipal.setEnabled(true); //Activamos la ventana principal
        MiSemanaSanta01.ventanaPrincipal.setVisible(true); //Hacemos visible la ventana principal
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSiguienteImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteImagenActionPerformed
        System.out.println("" + numeroCristo);
        if(numeroCristo<10) numeroCristo++; //Hay 11 Cristos, solo avanzamos si es menor de 11
        if(numeroCristo == 10) jButtonSiguienteImagen.setEnabled(false);
            else jButtonAnteriorImagen.setEnabled(true);
        //Mostramos los datos del Cristo a seleccionar
        seleccionarCristo(numeroCristo);
        
        //jLabelPrecioCristo.setText("" + VentanaPrincipal.miHermandad.getMiCristo().getPrecio());
    }//GEN-LAST:event_jButtonSiguienteImagenActionPerformed

    private void jButtonAnteriorImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorImagenActionPerformed
        System.out.println("" + numeroCristo);
        if(numeroCristo > 1) numeroCristo--; //Hay 10 Cristos, solo retrocedemos si es mayor de 0
        if(numeroCristo == 1) jButtonAnteriorImagen.setEnabled(false);
            else jButtonSiguienteImagen.setEnabled(true);
        //Mostramos los datos del Cristo a seleccionar
        seleccionarCristo(numeroCristo);
        
        
    }//GEN-LAST:event_jButtonAnteriorImagenActionPerformed

    private void jButtonComprarImagenPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarImagenPActionPerformed
        //Activamos los botones
        //jButtonAnteriorImagen.setEnabled(true);
        numeroCristo = 1;
        seleccionarCristo(numeroCristo);
        jButtonSiguienteImagen.setEnabled(true);
        jButtonComprarImagen.setEnabled(true);
        jButtonComprarImagenP.setEnabled(false);
        jButtonComprarPasoP.setEnabled(false);
    }//GEN-LAST:event_jButtonComprarImagenPActionPerformed

    private void jButtonComprarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarImagenActionPerformed
        this.setAlwaysOnTop(false);
        if(VentanaPrincipal.miHermandad.getDinero() < VentanaPrincipal.arrayCristos[numeroCristo-1].getPrecio())
        { //La hermandad no tiene dinero
            JOptionPane.showConfirmDialog(null, "No tienes dinero suficiente para comprar esta imagen.", "IMAGEN CRISTO", JOptionPane.DEFAULT_OPTION);
        } else { //La hermandad tiene dinero
            int opcion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que quieres comprar esta imagen?\n", "COMPRAR IMAGEN", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, imagenesCristo);
            //Después restamos el dinero y aumentamos la popularidad, siempre que aceptemos
            if(opcion == 0) { //Esto es que ha pulsado SÍ
                //Guardamos los datos de la imagen adquirida 
                VentanaPrincipal.miHermandad.setCristo(numeroCristo);
                JOptionPane.showMessageDialog(null, "Has comprado una imagen titular para tu hermandad.", "CRISTO", JOptionPane.OK_OPTION, imagenesCristo);
                
                //Modificamos el estado de los botones
                jButtonSiguienteImagen.setEnabled(false);
                jButtonComprarImagen.setEnabled(false);
                jButtonComprarPaso.setEnabled(false);
                jButtonAnteriorPaso.setEnabled(false);
                jButtonComprarImagenP.setEnabled(true);
                jButtonComprarPasoP.setEnabled(true);
                
                //Actualizamos el dinero y la popularidad de la hermandad
                VentanaPrincipal.miHermandad.setDinero(VentanaPrincipal.miHermandad.getDinero() - VentanaPrincipal.arrayCristos[numeroCristo-1].getPrecio()); //Actualizamos el dinero
                MiSemanaSanta01.ventanaPrincipal.jTextFieldDinero.setText("" + VentanaPrincipal.miHermandad.getDinero()); //Actualizamos el jlabel
                //Comprar un Cristo sube la popularidad como si donáramos 1000 euros
                int subidaPopularidad = VentanaPrincipal.miHermandad.calcularPopularidad(1000); //Calculamos cuánto sube la popularidad
                MiSemanaSanta01.ventanaPrincipal.escribirHistorico("Has comprado una imagen titular para tu hermandad.\n\n");
            }
        }
        //System.out.println("Precio" + VentanaPrincipal.arrayCristos[numeroCristo-1].getPrecio());
    }//GEN-LAST:event_jButtonComprarImagenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButtonAnteriorImagen;
    private javax.swing.JButton jButtonAnteriorPaso;
    public javax.swing.JButton jButtonComprarImagen;
    private javax.swing.JButton jButtonComprarImagenP;
    private javax.swing.JButton jButtonComprarPaso;
    private javax.swing.JButton jButtonComprarPasoP;
    public javax.swing.JButton jButtonSiguienteImagen;
    private javax.swing.JButton jButtonSiguientePaso;
    private javax.swing.JCheckBox jCheckBoxCristoSeleccionado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAltura;
    private javax.swing.JLabel jLabelAlturaCristo;
    private javax.swing.JLabel jLabelImagenesCristo;
    private javax.swing.JLabel jLabelMaterialCristo;
    private javax.swing.JLabel jLabelNCristo;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelPesoCristo;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelPrecioCristo;
    public javax.swing.JPanel jPanelComprarCristo;
    private javax.swing.JPanel jPanelComprarPaso;
    private javax.swing.JPanel jPanelCristo;
    private javax.swing.JPanel jPanelImagenesCristo;
    private javax.swing.JPanel jPanelPalio;
    private javax.swing.JPanel jPanelPaso;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public void seleccionarCristo(int numeroCristo) {
        imagenesCristo = new ImageIcon(getClass().getResource(cadena1 + "0" + numeroCristo + cadena2));
        jLabelImagenesCristo.setIcon(VentanaPrincipal.arrayCristos[numeroCristo-1].getImagen());
        jLabelPrecioCristo.setText("" + VentanaPrincipal.arrayCristos[numeroCristo-1].getPrecio());
        jLabelMaterialCristo.setText("" + VentanaPrincipal.arrayCristos[numeroCristo-1].getMaterial());
        jLabelAlturaCristo.setText("" + VentanaPrincipal.arrayCristos[numeroCristo-1].getAltura());
        jLabelPesoCristo.setText("" + VentanaPrincipal.arrayCristos[numeroCristo-1].getPeso());
        
        //Vamos a comprobar si es la imagen actual de la hermandad
        if(VentanaPrincipal.miHermandad.getCristo() == numeroCristo) {
            jCheckBoxCristoSeleccionado.setSelected(true);
            jButtonComprarImagen.setEnabled(false);
        } else {
            jCheckBoxCristoSeleccionado.setSelected(false);
            jButtonComprarImagen.setEnabled(true);
        }
        
        jLabelNCristo.setText(numeroCristo + " de " + VentanaPrincipal.arrayCristos.length);
        
    }
}
