/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misemanasanta01;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import static javax.swing.SwingConstants.CENTER;
import javax.swing.border.LineBorder;
import javax.swing.border.MatteBorder;

/**
 *
 * @author ManuSobremesa
 */
public class Plano extends javax.swing.JLayeredPane {

    /**
     * Creates new form Plano
     */
    
    public JLabel[][] casillasMapa;
    Icon casillaAzul;
    
    public Plano() {
        initComponents();
        
        casillasMapa = new JLabel[80][60];
        
        casillaAzul = new ImageIcon(getClass().getResource("/misemanasanta01/Graficos/casillaAzul.png"));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void rellenarMapa() {
    
        for(int x=0;x<80;x++) {
            for(int y=0;y<60;y++) {
                //casillasMapa[x][y] = null;
                casillasMapa[x][y].setText(""+x+""+y);
                casillasMapa[x][y].setSize(10, 10);
                casillasMapa[x][y].setLocation(x+(10*x), y+(10*y));
    
                //Añadimos las casillas al mapa-jPanel1
                this.add(casillasMapa[x][y]);
                    
            }
        }
    }
    public void rellenarMapaSinCoordenadas() {
    
        for(int x=0;x<80;x++) {
            for(int y=0;y<60;y++) {
                //casillasMapa[x][y] = null;
                casillasMapa[x][y].setText("");
                casillasMapa[x][y].setSize(10, 10);
                casillasMapa[x][y].setLocation(x + (10*x),y + (10*y));
                //casillasMapa[x][y].setLocation((10*x), (10*y)); //Esta linea si no queremos dejar huecos
    
                this.add(casillasMapa[x][y]);
                //jPanel1.add(casillasMapa[x][y]);
                
            }
        }
    }
    
    public void inicializarMapaVacio() {
    
        Color color = new Color(255, 255, 255, 0);
        
        for(int x=0;x<80;x++) {
            for(int y=0;y<60;y++) {
                casillasMapa[x][y] = new JLabel("");
                casillasMapa[x][y].setHorizontalAlignment(JLabel.CENTER);
                //casillasMapa[x][y].setForeground(new Color(220, 220, 220, 220));
                casillasMapa[x][y].setOpaque(true);
                casillasMapa[x][y].setBackground(Color.LIGHT_GRAY);//
            }
        }
    }
    
    public void inicializarMapaConTextoLabel() {
    
        Color color = new Color(255, 255, 255, 0);
        
        for(int x=0;x<80;x++) {
            for(int y=0;y<60;y++) {
                casillasMapa[x][y] = new JLabel("Label"+x+""+y);
                casillasMapa[x][y].setHorizontalAlignment(CENTER);
                casillasMapa[x][y].setForeground(Color.WHITE);
                casillasMapa[x][y].setOpaque(true);
                casillasMapa[x][y].setBackground(Color.LIGHT_GRAY);//
                //casillasMapa[x][y].setComponentZOrder(this, 1);
                //casillasMapaGraficosPJ[x][y].setComponentZOrder(this, 2);
                //casillasMapa[x][y].setBorder();
            }
        }
    }
    
    public void dibujaEdificio() {
        
        Color color = new Color(0, 0, 0, 0);
        
        for(int x=0;x<80;x++) {
            for(int y=0;y<60;y++) {
                casillasMapa[x][y] = new JLabel("");
                casillasMapa[x][y].setHorizontalAlignment(JLabel.CENTER);
                //casillasMapa[x][y].setForeground(Color.WHITE);
                casillasMapa[x][y].setOpaque(true);
                casillasMapa[x][y].setBackground(Color.LIGHT_GRAY);//
                //casillasMapa[x][y].setIcon(casillaAzul);
            }
        }
        for(int x=60;x<66;x++) {
            for(int y=30;y<37;y++) {
                casillasMapa[x][y].setBackground(Color.BLUE);//                
            }
        }
        
        for(int x=20;x<36;x++) {
            for(int y=10;y<12;y++) {
                casillasMapa[x][y].setBackground(Color.GRAY);
                casillasMapa[x][y].setBorder(new LineBorder(Color.GRAY));
                casillasMapa[x][y].setBorder(new MatteBorder(1,1,1,1,Color.BLACK));
            }
        }
    }

}
