/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misemanasanta01;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ManuPortatil
 */
public class SedecanonicaGUI extends javax.swing.JFrame {

    //Instancias de las iglesias
    static public ImageIcon iconoSantaMaria, iconoSanFrancisco, iconoSanJose, iconoSantaBarbara, iconoSanAgustin, iconoIglesiaElegida;
    //Variable para guardar la sede Canónica como texto
    //static public String sede;
    //Imagen de icono para los JOptionPane
    static public ImageIcon iconoDialogos;
    
    /**
     * Creates new form Finanzas
     */
    public SedecanonicaGUI() {
        initComponents();
        //Le ponemos un marco la ventana
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(3, 3, 3, 3, Color.BLUE));
        
        //Guardamos las imágenes de las Iglesias
        iconoSantaMaria = new ImageIcon(getClass().getResource("/misemanasanta01/Graficos/SantaMaria225x170.jpg"));
        iconoSantaBarbara = new ImageIcon(getClass().getResource("/misemanasanta01/Graficos/SantaBarbara225x170.jpg"));
        iconoSanJose = new ImageIcon(getClass().getResource("/misemanasanta01/Graficos/SanJose225x170.jpg"));
        iconoSanFrancisco = new ImageIcon(getClass().getResource("/misemanasanta01/Graficos/SantaFrancisco225x170.jpg"));
        iconoSanAgustin = new ImageIcon(getClass().getResource("/misemanasanta01/Graficos/SanAgustin225x170.jpg"));
        
        //Inicializamos la iglesia por defecto
        iconoIglesiaElegida = iconoSantaMaria;
        iconoDialogos = new ImageIcon(getClass().getResource("/misemanasanta01/Graficos/calendario.png"));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jPanelEscogeIglesia = new javax.swing.JPanel();
        jLabelEscogeIglesia = new javax.swing.JLabel();
        jComboBoxEligeIglesiia = new javax.swing.JComboBox<>();
        jButtonEstablecer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonCambiarSede = new javax.swing.JButton();
        jLabelIglesia = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxSemanaCultos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxMesFCristo = new javax.swing.JComboBox<>();
        jButtonSemanaCultos = new javax.swing.JButton();
        jButtonMesFCristo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxMesFVirgen = new javax.swing.JComboBox<>();
        jButtonMesFVirgen = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setUndecorated(true);

        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jPanelEscogeIglesia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escoger Iglesia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("VAGRounded BT", 0, 12), new java.awt.Color(255, 102, 0))); // NOI18N

        jLabelEscogeIglesia.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabelEscogeIglesia.setForeground(new java.awt.Color(0, 0, 153));
        jLabelEscogeIglesia.setText("Escoge Iglesia: ");

        jComboBoxEligeIglesiia.setBackground(new java.awt.Color(255, 204, 255));
        jComboBoxEligeIglesiia.setFont(new java.awt.Font("Zolano Serif BTN", 1, 14)); // NOI18N
        jComboBoxEligeIglesiia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basílica Menor de Santa María la Mayor", "Parroquia de San Francisco", "Parroquia de San Agustín", "Parroquia de Santa Bárbara", "Parroquia de San José" }));
        jComboBoxEligeIglesiia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEligeIglesiiaActionPerformed(evt);
            }
        });

        jButtonEstablecer.setBackground(new java.awt.Color(255, 204, 0));
        jButtonEstablecer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonEstablecer.setText("ESTABLECER");
        jButtonEstablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstablecerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel2.setText("Influencia:");

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel3.setText("Aforo:");

        jButtonCambiarSede.setBackground(new java.awt.Color(255, 51, 0));
        jButtonCambiarSede.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCambiarSede.setText("CAMBIAR DE SEDE");
        jButtonCambiarSede.setEnabled(false);
        jButtonCambiarSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarSedeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEscogeIglesiaLayout = new javax.swing.GroupLayout(jPanelEscogeIglesia);
        jPanelEscogeIglesia.setLayout(jPanelEscogeIglesiaLayout);
        jPanelEscogeIglesiaLayout.setHorizontalGroup(
            jPanelEscogeIglesiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEscogeIglesiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEscogeIglesiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEscogeIglesiaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCambiarSede)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEstablecer))
                    .addGroup(jPanelEscogeIglesiaLayout.createSequentialGroup()
                        .addGroup(jPanelEscogeIglesiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEscogeIglesiaLayout.createSequentialGroup()
                                .addComponent(jLabelEscogeIglesia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxEligeIglesiia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 140, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelEscogeIglesiaLayout.setVerticalGroup(
            jPanelEscogeIglesiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEscogeIglesiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEscogeIglesiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEscogeIglesia)
                    .addComponent(jComboBoxEligeIglesiia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanelEscogeIglesiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCambiarSede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEstablecer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabelIglesia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/misemanasanta01/Graficos/SantaMaria225x170.jpg"))); // NOI18N
        jLabelIglesia.setText("jLabel1");
        jLabelIglesia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cultos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("VAGRounded BT", 0, 12), new java.awt.Color(204, 102, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel1.setText("Semana de Cultos: ");

        jComboBoxSemanaCultos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1ª de Cuaresma", "2ª de Cuaresma", "3ª de Cuaresma", "4ª de Cuaresma", "5ª de Cuaresma" }));

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel4.setText("Mes Festividad Cristo: ");

        jComboBoxMesFCristo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jButtonSemanaCultos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSemanaCultos.setText("Establecer");
        jButtonSemanaCultos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSemanaCultosActionPerformed(evt);
            }
        });

        jButtonMesFCristo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonMesFCristo.setText("Establecer");
        jButtonMesFCristo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesFCristoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel5.setText("Mes Festividad Virgen: ");

        jComboBoxMesFVirgen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jButtonMesFVirgen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonMesFVirgen.setText("Establecer");
        jButtonMesFVirgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesFVirgenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxMesFVirgen, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxSemanaCultos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxMesFCristo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSemanaCultos)
                    .addComponent(jButtonMesFCristo)
                    .addComponent(jButtonMesFVirgen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxSemanaCultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSemanaCultos))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxMesFCristo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMesFCristo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxMesFVirgen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMesFVirgen))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelEscogeIglesia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelIglesia, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalir)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabelIglesia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanelEscogeIglesia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose(); //Destruimos la instancia de esta ventana
        MiSemanaSanta01.ventanaPrincipal.setEnabled(true); //Activamos la ventana principal
        MiSemanaSanta01.ventanaPrincipal.setVisible(true); //Hacemos visible la ventana principal
        System.out.println(jComboBoxEligeIglesiia.getSelectedItem().toString());
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonEstablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstablecerActionPerformed
        this.setAlwaysOnTop(false);
        //Guardamos La iglesia en los datos de la hermandad
        VentanaPrincipal.miHermandad.setSedeCanonica(jComboBoxEligeIglesiia.getSelectedItem().toString());
        JOptionPane.showMessageDialog(null, "Se ha establecido la Sede Canónica de la Hermandad.", "IGLESIA SELECCIONADA", JOptionPane.OK_OPTION, iconoIglesiaElegida);
        //Desactivamos opciones para escoger Sede Canónica
        jButtonEstablecer.setEnabled(false);
        jComboBoxEligeIglesiia.setEnabled(false);
        jButtonCambiarSede.setEnabled(true); //Activamos el botón para cambiar de sede canónica
        //this.dispose(); //Destruimos la instancia de esta ventana
        //MiSemanaSanta01.ventanaPrincipal.setEnabled(true); //Activamos la ventana principal
        //MiSemanaSanta01.ventanaPrincipal.setVisible(true); //Hacemos visible la ventana principal
        MiSemanaSanta01.ventanaPrincipal.escribirHistorico("Se ha establecido la Sede Canónica de la Hermandad.\n\n");
    }//GEN-LAST:event_jButtonEstablecerActionPerformed

    private void jComboBoxEligeIglesiiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEligeIglesiiaActionPerformed
        if(jComboBoxEligeIglesiia.getSelectedIndex() == 0) 
            iconoIglesiaElegida = iconoSantaMaria;
            //jLabelIglesia.setIcon(iconoSantaMaria);
        if(jComboBoxEligeIglesiia.getSelectedIndex() == 1)
            iconoIglesiaElegida = iconoSanFrancisco;
            //jLabelIglesia.setIcon(iconoSanFrancisco);
        if(jComboBoxEligeIglesiia.getSelectedIndex() == 2)
            iconoIglesiaElegida = iconoSanAgustin;
            //jLabelIglesia.setIcon(iconoSanAgustin);
        if(jComboBoxEligeIglesiia.getSelectedIndex() == 3)
            iconoIglesiaElegida = iconoSantaBarbara;
            //jLabelIglesia.setIcon(iconoSantaBarbara);
        if(jComboBoxEligeIglesiia.getSelectedIndex() == 4)
            iconoIglesiaElegida = iconoSanJose;
            //jLabelIglesia.setIcon(iconoSanJose);
            
        jLabelIglesia.setIcon(iconoIglesiaElegida);
    }//GEN-LAST:event_jComboBoxEligeIglesiiaActionPerformed

    private void jButtonSemanaCultosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSemanaCultosActionPerformed
        this.setAlwaysOnTop(false);
        //Guardamos La iglesia en los datos de la hermandad
        VentanaPrincipal.miHermandad.setSemanaCultos(jComboBoxSemanaCultos.getSelectedIndex());
        JOptionPane.showMessageDialog(null, "Se ha establecido la Semana de Cultos de la Hermandad.", "CULTOS SELECCIONADOS", JOptionPane.OK_OPTION, iconoDialogos);
        //this.dispose(); //Destruimos la instancia de esta ventana
        //MiSemanaSanta01.ventanaPrincipal.setEnabled(true); //Activamos la ventana principal
        //MiSemanaSanta01.ventanaPrincipal.setVisible(true); //Hacemos visible la ventana principal
        MiSemanaSanta01.ventanaPrincipal.escribirHistorico("Se ha establecido la Semana de Cultos de la Hermandad.\n\n");
    }//GEN-LAST:event_jButtonSemanaCultosActionPerformed

    private void jButtonCambiarSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarSedeActionPerformed
        jButtonEstablecer.setEnabled(true);
        jComboBoxEligeIglesiia.setEnabled(true);
        jButtonCambiarSede.setEnabled(false);
    }//GEN-LAST:event_jButtonCambiarSedeActionPerformed

    private void jButtonMesFCristoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesFCristoActionPerformed
        this.setAlwaysOnTop(false);
        //Guardamos La iglesia en los datos de la hermandad
        VentanaPrincipal.miHermandad.setFestividadCristo(jComboBoxMesFCristo.getSelectedIndex());
        JOptionPane.showMessageDialog(null, "Se ha establecido el mes de la Festividad de la Imagen Titular de Cristo.", "FESTIVIDAD CRISTO", JOptionPane.OK_OPTION, iconoDialogos);
        MiSemanaSanta01.ventanaPrincipal.escribirHistorico("Se ha establecido el mes de la Festividad de la Imagen Titular de Cristo.\n\n");
    }//GEN-LAST:event_jButtonMesFCristoActionPerformed

    private void jButtonMesFVirgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesFVirgenActionPerformed
        this.setAlwaysOnTop(false);
        //Guardamos La iglesia en los datos de la hermandad
        VentanaPrincipal.miHermandad.setFestividadVirgen(jComboBoxMesFVirgen.getSelectedIndex());
        JOptionPane.showMessageDialog(null, "Se ha establecido el mes de la Festividad de la Imagen Titular de Virgen", "FESTIVIDAD VIRGEN", JOptionPane.OK_OPTION, iconoDialogos);
        MiSemanaSanta01.ventanaPrincipal.escribirHistorico("Se ha establecido el mes de la Festividad de la Imagen Titular de Palio.\n\n");
    }//GEN-LAST:event_jButtonMesFVirgenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonCambiarSede;
    public javax.swing.JButton jButtonEstablecer;
    private javax.swing.JButton jButtonMesFCristo;
    private javax.swing.JButton jButtonMesFVirgen;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSemanaCultos;
    public javax.swing.JComboBox<String> jComboBoxEligeIglesiia;
    public javax.swing.JComboBox<String> jComboBoxMesFCristo;
    public javax.swing.JComboBox<String> jComboBoxMesFVirgen;
    public javax.swing.JComboBox<String> jComboBoxSemanaCultos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelEscogeIglesia;
    private javax.swing.JLabel jLabelIglesia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelEscogeIglesia;
    // End of variables declaration//GEN-END:variables
}
